version: "3.7"
  
networks:
  chrome-devtools-frontend-network:
    driver: overlay

services:
  chrome-devtools-frontend:
    image: awardell/chrome-devtools-frontend
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
        mode: ingress
    networks:
      - chrome-devtools-frontend-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
